# config file

spring:
  application:
    name: springboot-template
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
server:
  port: 8081
