# config file

spring:
  application:
    name: springboot-template
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

knife4j:
  enable: false
  openapi:
    title: "Interface"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory